// src/lib/data.ts
export const mockCourses = [
  {
    id: "1",
    name: "Curso de Next.js",
    description: "Aprende a crear aplicaciones con Next.js",
    category: "Desarrollo Web",
    duration: "10 horas",
    imageSrc: "/liderazgo.jpg",
    active: true,
  },
  {
    id: "2",
    name: "Diseño UX/UI",
    description: "Domina los principios del diseño de interfaces",
    category: "Diseño",
    duration: "8 horas",
    active: false,
    //imageSrc: "/uxui.png",
  },
  {
    id: "3",
    name: "Marketing Digital",
    description: "Estrategias efectivas para el marketing online",
    category: "Marketing",
    duration: "12 horas",
    active: true,
    //imageSrc: "/marketing.jpg",
  },
  {
    id: "4",
    name: "Ofimática Básica",
    description: "Manejo de herramientas de oficina como Word y Excel",
    category: "Ofimática",
    duration: "6 horas",
    active: true,
    //imageSrc: "/ofimatica.png",
  },
  {
    id: "5",
    name: "Bases de Datos SQL",
    description: "Aprende a diseñar y consultar bases de datos SQL",
    category: "Base de Datos",
    duration: "9 horas",
    active: false,
    //imageSrc: "/sql.jpg",
  },
  {
    id: "6",
    name: "React Avanzado",
    description: "Profundiza en hooks, context y optimización de React",
    category: "Desarrollo Web",
    duration: "14 horas",
    active: true,
    //imageSrc: "/react.png",
  },
  {
    id: "7",
    name: "Illustrator para Diseño",
    description: "Diseña gráficos vectoriales profesionales",
    category: "Diseño",
    duration: "7 horas",
    active: true,
    //imageSrc: "/illustrator.jpg",
  },
  {
    id: "8",
    name: "SEO y Posicionamiento Web",
    description: "Optimiza tu sitio web para buscadores",
    category: "Marketing",
    duration: "10 horas",
    active: true,
    //imageSrc: "/seo.png",
  },
  {
    id: "9",
    name: "Excel Intermedio",
    description: "Funciones avanzadas y manejo de datos en Excel",
    category: "Ofimática",
    duration: "8 horas",
    active: false,
    //imageSrc: "/excel.jpg",
  },
  {
    id: "10",
    name: "MongoDB para Desarrolladores",
    description: "Gestión de bases de datos NoSQL con MongoDB",
    category: "Base de Datos",
    duration: "11 horas",
    active: true,
    //imageSrc: "/mongodb.png",
  },
];
